// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_germana_diana_medic");
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	precacheModel("xmodel/character_germana_diana_medic");
	precacheModel("xmodel/viewmodel_hands_russian");
}
