// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_american_normandy05");
	self attach("xmodel/head_us_ranger_medic_wells", "", true);
	self.hatModel = "xmodel/helmet_us_ranger_generic";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_cloth");
}

precache()
{
	precacheModel("xmodel/playerbody_american_normandy05");
	precacheModel("xmodel/head_us_ranger_medic_wells");
	precacheModel("xmodel/helmet_us_ranger_generic");
	precacheModel("xmodel/viewmodel_hands_cloth");
}
