// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_africa01");
	self attach("xmodel/head_german_afrca_christoph", "", true);
	self.hatModel = "xmodel/helmet_german_africa";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_british_bare");
}

precache()
{
	precacheModel("xmodel/playerbody_german_africa01");
	precacheModel("xmodel/head_german_afrca_christoph");
	precacheModel("xmodel/helmet_german_africa");
	precacheModel("xmodel/viewmodel_hands_british_bare");
}
