// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_winterdark");
	self attach("xmodel/head_german_normandy_ericp", "", true);
	self.hatModel = "xmodel/helmet_german_winter_dark";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_german_winter");
}

precache()
{
	precacheModel("xmodel/playerbody_german_winterdark");
	precacheModel("xmodel/head_german_normandy_ericp");
	precacheModel("xmodel/helmet_german_winter_dark");
	precacheModel("xmodel/viewmodel_hands_german_winter");
}
